apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: color-jelly-rush

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: color-jelly-rush
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/eilodon/color-jelly-rush
    newTag: latest
