apiVersion: v1
kind: Service
metadata:
  name: color-jelly-rush
  namespace: color-jelly-rush
  labels:
    app.kubernetes.io/name: color-jelly-rush
    app.kubernetes.io/component: game-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 2567
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: color-jelly-rush
